export {
  createConsultation,
  grantConsent,
  revokeConsent,
  getConsentStatus,
  isCaptureAuthorized,
  assertCaptureAuthorized,
  listConsultationsByPatient,
  setConsultationStatus,
  getConsultationMeta,
  setConsultationBoardMode,
  setFinalReviewStatus,
  ConsentRequiredError,
  type ConsentStatus,
  type ConsultationSummary,
  type ConsultationMeta,
  type BoardMode,
  type FinalReviewStatus,
} from './consent';
