export {
  computeAge,
  createPatient,
  updatePatient,
  loadPatient,
  listPatients,
  addBodyComposition,
  addLabExam,
  listBodyComposition,
  listLabExam,
  // Exames personalizados por paciente + metas corporais
  setCustomExamDefs,
  loadCustomExamDefs,
  setBodyGoal,
  loadCurrentBodyGoal,
  // E12 — metas nutricionais & food log
  setNutritionGoal,
  loadCurrentNutritionGoal,
  listNutritionGoalHistory,
  addFoodLogEntry,
  findLatestFoodLogEntry,
  updateFoodLogEntryValues,
  listFoodLogByDay,
  sumFoodLogForDay,
  type Patient,
  type PatientInput,
  type WriteOrigin,
  type Measurement,
  type MeasurementInput,
  type BodyCompositionValues,
  type LabExamValues,
  type CustomExamDef,
  type BodyGoalValues,
  type BodyGoal,
  type NutritionGoalValues,
  type NutritionGoal,
  type FoodConfidence,
  type FoodLogValues,
  type FoodLogEntry,
  type FoodLogInput,
  type DailyProgress,
} from './patients';
