export {
  computeAge,
  createPatient,
  updatePatient,
  loadPatient,
  listPatients,
  addBodyComposition,
  addLabExam,
  listBodyComposition,
  listLabExam,
  // E12 — metas nutricionais & food log
  setNutritionGoal,
  loadCurrentNutritionGoal,
  listNutritionGoalHistory,
  addFoodLogEntry,
  listFoodLogByDay,
  sumFoodLogForDay,
  type Patient,
  type PatientInput,
  type WriteOrigin,
  type Measurement,
  type MeasurementInput,
  type BodyCompositionValues,
  type LabExamValues,
  type NutritionGoalValues,
  type NutritionGoal,
  type FoodConfidence,
  type FoodLogValues,
  type FoodLogEntry,
  type FoodLogInput,
  type DailyProgress,
} from './patients';
