export {
  computeAge,
  createPatient,
  updatePatient,
  loadPatient,
  listPatients,
  countPatients,
  softDeletePatient,
  addBodyComposition,
  addLabExam,
  updateBodyComposition,
  updateLabExam,
  softDeleteBodyComposition,
  softDeleteLabExam,
  listBodyComposition,
  listLabExam,
  // Exames personalizados por paciente + metas corporais
  setCustomExamDefs,
  loadCustomExamDefs,
  setBodyGoal,
  loadCurrentBodyGoal,
  // E12 — metas nutricionais & food log
  setNutritionGoal,
  loadCurrentNutritionGoal,
  listNutritionGoalHistory,
  addFoodLogEntry,
  findLatestFoodLogEntry,
  updateFoodLogEntryValues,
  listFoodLogByDay,
  sumFoodLogForDay,
  // Água + sono via Telegram (2026-07-20)
  addWaterLog,
  listWaterLogByDay,
  sumWaterForDay,
  listWaterHistory,
  addSleepEvent,
  findLastSleepSession,
  listSleepSessions,
  classifySleepDuration,
  sleepTargetFromGoal,
  DEFAULT_SLEEP_TARGET,
  type Patient,
  type PatientInput,
  type WriteOrigin,
  type Measurement,
  type MeasurementInput,
  type BodyCompositionValues,
  type LabExamValues,
  type CustomExamDef,
  type BodyGoalValues,
  type BodyGoal,
  type NutritionGoalValues,
  type NutritionGoal,
  type FoodConfidence,
  type FoodLogValues,
  type FoodLogEntry,
  type FoodLogInput,
  type DailyProgress,
  type WaterLogEntry,
  type WaterProgress,
  type SleepEventKind,
  type SleepQuality,
  type SleepSession,
  type SleepTargetRange,
} from './patients';
