export {
  generateNoteDraft,
  saveNote,
  loadNote,
  saveSynthesis,
  listSyntheses,
  saveTranscriptSegment,
  listTranscriptFinals,
  countTranscriptFinals,
  auditTranscriptPersistStart,
  saveTranscriptReview,
  loadTranscriptReview,
  saveConsultationRecord,
  loadConsultationRecord,
  type ClinicalNote,
  type BoardSynthesis,
  type TranscriptReview,
  type ConsultationRecord,
} from './notes';
