export {
  handleStart,
  handlePhoto,
  handleCorrection,
  handleAte,
  handleMealChoice,
  handleMealCommand,
  handleToday,
  handleGoal,
  handleUpdate,
  type BotButton,
  type BotDeps,
  type BotReply,
  type BotUpdate,
} from './bot';
